export const allCards = [
    {
        id: 0,
        title: 'Scholarships for high education',
        shortTitle: 'Scholarships',
        cost: 40000,
        description: 'We will use $40,000 USD to provide scholarships to young adults of the neighbourhood, so they can have access to higher education and better job opportunities. In return, the young adults will give back to the neighbourhood social work hours.',
        image: require('../img/education/Neutral.jpg'),
        imageBad: require('../img/education/Bad.jpg'),
        imageGood: require('../img/education/Good.jpg'),
    },
    {
        id: 1,
        title: 'A football field for our kids',
        shortTitle: 'Football',
        cost: 50000,
        description: 'We will use $50,000 USD to build a football field in the neighbourhood so our kids have a safe space to play.',
        image: require('../img/football/Neutral.jpg'),
        imageBad: require('../img/football/Bad.jpg'),
        imageGood: require('../img/football/Good.jpg'),
    },
    {
        id: 2,
        title: 'A healthcare programme for the elderly',
        shortTitle: 'Healthcare',
        cost: 20000,
        description: 'We will use $20,000 USD to build a healthcare programme for the elderly.',
        image: require('../img/health/Neutral.jpg'),
        imageBad: require('../img/health/Bad.jpg'),
        imageGood: require('../img/health/Good.jpg'),
    },
    {
        id: 3,
        title: 'Improve the household conditions',
        shortTitle: 'Houses',
        cost: 80000,
        description: 'We will use $80,000 USD to improve the household conditions of the neighbourhood.',
        image: require('../img/housing/Neutral.jpg'),
        imageBad: require('../img/housing/Bad.jpg'),
        imageGood: require('../img/housing/Good.jpg'),
    },
    {
        id: 4,
        title: 'Building better roads for pedestrians',
        shortTitle: 'Roads',
        cost: 30000,
        description: 'We will use $30,000 to build a road for pedestrians.',
        image: require('../img/roads/Neutral.jpg'),
        imageBad: require('../img/roads/Bad.jpg'),
        imageGood: require('../img/roads/Good.jpg'),
    },
]

