export const allCards = [
    {
        id: 0,
        title: 'Educación para nuestros jóvenes',
        shortTitle: 'Educación',
        cost: 1500000000,
        description: 'Utilizaremos $1500’000.000 para proporcionar becas a jóvenes de la comuna, para que puedan tener acceso a educación superior y mejores oportunidades laborales. A cambio, los jóvenes aportarán horas de trabajo social al barrio.',
        image: require('../img/education/Neutral.jpg'),
        imageBad: require('../img/education/Bad.jpg'),
        imageGood: require('../img/education/Good.jpg'),
    },
    {
        id: 1,
        title: 'Un campo de fútbol para nuestros niños',
        shortTitle: 'Fútbol,
        cost: 200000000,
        description: 'Utilizaremos $200’000.000 para construir un campo de fútbol en el vecindario, en donde nuestros niños puedan jugar.',
        image: require('../img/football/Neutral.jpg'),
        imageBad: require('../img/football/Bad.jpg'),
        imageGood: require('../img/football/Good.jpg'),
    },
    {
        id: 2,
        title: 'Un programa de salud para nuestros adultos mayores',
        shortTitle: 'Salud',
        cost: 300000000,
        description: 'Utilizaremos $300’000.000 para construir un programa integral de atención médica para nuestros adultos mayores.',
        image: require('../img/health/Neutral.jpg'),
        imageBad: require('../img/health/Bad.jpg'),
        imageGood: require('../img/health/Good.jpg'),
    },
    {
        id: 3,
        title: 'Mejores viviendas para nuestras familias',
        shortTitle: 'Viviendas',
        cost: 2000000000,
        description: 'Utilizaremos $2.000’000.000 para mejorar las condiciones de las viviendas de la comuna..',
        image: require('../img/housing/Neutral.jpg'),
        imageBad: require('../img/housing/Bad.jpg'),
        imageGood: require('../img/housing/Good.jpg'),
    },
    {
        id: 4,
        title: 'Mejores caminos para nuestros peatones',
        shortTitle: 'Caminos',
        cost: 1000000000,
        description: 'Utilizaremos $1.000’000.000 para construir mejores caminos peatonales en la comuna.',
        image: require('../img/roads/Neutral.jpg'),
        imageBad: require('../img/roads/Bad.jpg'),
        imageGood: require('../img/roads/Good.jpg'),
    },
]

